### ISSUE TITLE
Direct link cloudmailru error

### ISSUE THREAD

**Issue by muhammedfurkan** [RaphielGang/Telegram-UserBot#165]
**Describe the bug**
```
ERROR:telethon.client.updates:Unhandled exception on direct_link_generator
Traceback (most recent call last):
 File "/app/.heroku/python/lib/python3.7/site-packages/telethon/client/updates.py", line 416, in _dispatch_update
await callback(event)
File "stdplugins/direct_link.py", line 49, in direct_link_generator
  reply += cm_ru(link)
   File "stdplugins/direct_link.py", line 197, in cm_ru
     result = result.splitlines()[-1]
 IndexError: list index out of range

```

**Screenshots**
![image](https://user-images.githubusercontent.com/9547040/61936861-3e7f5c00-af96-11e9-9888-39dabee9f6b8.png)

**Python Version**
3.7.3

**Comment by baalajimaestro** [comment]
Known issue, will be looked in
